### PR TITLE
New Folder structure as well as new fprime guides

### PR DESCRIPTION
**Pull request by Ruben1729**
I noticed while working on the repo that the code was a bit all over the place. I have done a few things to organize it:

Firstly, I created three folders containing the three "subjects" that we are discussing in the main page. These folders are "fprime-guide" containing all the different guides and documentation for fprime, "git-guide" containing the guide @laurentlaurent provided us with and "charts" for the diagrams.

Secondly, I took Laurent's guide and split it into smaller sections. It allows users to find themselves quicker but also it's easier to maintain the docs this way. Each file contains a different subject. For example in the "/git-guide/basic-guide.md" you can find all of the basics for using git.

I followed this exact same process for fprime related guides, once again, making the docs easier to read but also easier to manage.

Thirdly, I added some documentation for the architecture (Components, ports, commands, etc). I haven't finished this section but I want to run the math tutorial project before our meeting today so I'm putting it aside for now.

Additionally, I included the change that @AFknUsername had done earlier by adding "pip3 install wheel" right after the pytest and numpy.

### CODE REVIEW

**Comment by laurent-lao** [comment]
@Ruben1729 There is a method to the madness with the external files like the git guide (and the planned import of the external NASA Fprime tutorials).

In the case of the Git Guide, the file at docs/raw-redirect/laurent-git-guide.md looks like this:
```
<!-- markdownlint-disable -->

<!--  If you clicked on "Edit on Github"
      Request an edit at https://github.com/laurentlaurent/guides/issues
      This page's job is to redirect to the raw md file on another repo -->

Embedded redirect from [Laurent's Git Guide](https://docs.laurentlao.com/#/guides/guide-git)

[Git Guide](https://raw.githubusercontent.com/laurentlaurent/guides/master/guides/guide-git.md)
```

Basically, using docsify, I am able to pull an external `.md` file to act like a page in the docs. This allows Docsify to always pull the latest version of the `.md` file (which then makes it easier for me to update the git guide at only one spot).

**Comment by laurent-lao** [comment]
@Ruben1729 Additionally: 
* The information on [Building for BBB](https://docs.sc-odin.now.sh/#/fprime/guide-setting-up-fprime?id=building-for-bbb) is missing (I couldn't find them)
* The link at `Fprime Guide > Introduction > Quick Installation Guide > 'Note: If you wish to see a more in depth guide click here'` is broken

* The search feature on your branch finds things better in the Git Guide than on the master branch, that's a big plus 👍

**Comment by Ruben1729** [comment]
I know you were using your git guide but I just wanted to split your guide into smaller sections, mostly for it to be easier to navigate :) 

I'll add the BBB build thing in a sec, I wanted to also put it in a different file so that installation and build examples are separated and so I have it in a file it's just not linked yet.

I'll check the broken link and fix it in a sec :) I'll also create a new branch so that I'm not merging with master.

I'll cancel this PR for now.

**Comment by laurent-lao** [comment]
@Ruben1729 Final comments:
I agree that the docs folder structure was a mess. The reasons for that are two-fold:
* The docs were meant to be not exclusive to CDH, and we were waiting to on-board the other subsystems before fixing the hierarchy structure
* Docsify's search plugin is really dumb and can only search whatever is in the current sidebar. You can test that by typing `linux` at the homepage and then `linux` after you've clicked on `Fprime Guide` in the sidebar (not that it was any better in the current master haha)

**Comment by laurent-lao** [comment]
> I know you were using your git guide but I just wanted to split your guide into smaller sections, mostly for it to be easier to navigate :)

@Ruben1729
Yeah, it's definitely better with the way you structured it. We'll have to discuss the trade-offs between readability and extra overhead from modifying the guide. I think the current master's implementation is _fine_ (you get all the relevant headers listed on the side, so you can jump sections). It's definitely not the best, but it makes it easier to modify.

This would also apply to relevant pages we would `raw .md redirect` that comes directly from the NASA docs. Would readability be more important? or ensuring that the pages we linked are always up to date be more important?

**Pull request closed without merging**
